"""
Script to generate the complete, production-grade POT_PTQ_1B_reproduction.ipynb notebook.
"""

import json

cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# POT-PTQ: A Two-Step Power-of-Two Post-Training Quantization for ~1B LLMs\n",
            "\n",
            "**Full Reproduction Notebook** for **\"POT-PTQ: A Two-step Power-of-Two Post-training for LLMs\"** (Wang et al., arXiv:2507.11959, 2025).\n",
            "\n",
            "This notebook applies POT-PTQ to a real ~1-billion-parameter Hugging Face causal LM (`EleutherAI/pythia-1b` or `TinyLlama/TinyLlama_v1.1` or `meta-llama/Llama-3.2-1B`) on the **WikiText-2** benchmark (Sec. 5.1–5.2, Table 1).\n",
            "\n",
            "---\n",
            "### Paper Highlights & Algorithmic Foundation\n",
            "1. **Statistical Alignment (Sec. 2.2, Fig. 1)**: LLM weights follow bell-shaped distributions with exponential decay. Power-of-Two (PoT) provides finer logarithmic resolution near zero $(\\pm 2^E \\cdot S)$, matching LLM weights far better than uniform integer quantization.\n",
            "2. **Step 1: Parallel Data-Agnostic Scale Initialization (Algorithm 1, Sec. 3.2)**: Performs grid search over candidate multipliers $B = \\{0.01 \\cdot i \\mid i=1,\\dots,200\\}$ to find the optimal scale $s^* = s_0 \\cdot b^*$ that minimizes weight reconstruction MSE $\|W - \\hat{W}(b)\\|_2^2$.\n",
            "3. **Step 2: Data-Dependent Fine-Tuning (Algorithm 2, Sec. 3.3)**: Adjusts scales using learnable residual $\\hat{S} = S \\odot (1 + \\Gamma)$ via Straight-Through Estimator (STE) gradient propagation on minimal calibration data (e.g., 16–128 sequences) without full model retraining.\n",
            "4. **Hardware Bitwise Dequantization (Sec. 4, Fig. 4, Table 6)**: Implements IEEE 754 FP16 exponent integer addition $(E \\ll 10)$ and bitwise sign manipulation, achieving up to **3.67x** faster dequantization than uniform FP16 multiplication on CUDA GPUs."
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 0. Setup & Environment Verification"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import importlib.util, subprocess, sys\n",
            "\n",
            "def _ensure(pkg, pip_name=None):\n",
            "    if importlib.util.find_spec(pkg) is None:\n",
            "        subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", pip_name or pkg], check=True)\n",
            "\n",
            "_ensure(\"torch\")\n",
            "_ensure(\"transformers\")\n",
            "_ensure(\"datasets\")\n",
            "_ensure(\"accelerate\")\n",
            "\n",
            "import torch\n",
            "print(\"PyTorch Version:  \", torch.__version__)\n",
            "print(\"CUDA Available:   \", torch.cuda.is_available())\n",
            "if torch.cuda.is_available():\n",
            "    print(\"GPU Device:       \", torch.cuda.get_device_name(0))\n",
            "    print(f\"GPU Total VRAM:    {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB\")\n",
            "DEVICE = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
            "print(\"Execution Target: \", DEVICE)"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 1. Experiment & Quantization Configuration\n",
            "\n",
            "Default model: `EleutherAI/pythia-1b` (~1.01B parameters). Compatible with any Hugging Face CausalLM architecture (`TinyLlama/TinyLlama_v1.1`, `meta-llama/Llama-3.2-1B`, `Qwen/Qwen2.5-1.5B`, `facebook/opt-1.3b`, etc.)."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "# ---- Model Configuration ----\n",
            "MODEL_NAME  = \"EleutherAI/pythia-1b\"     # Real ~1B parameter LLM\n",
            "MODEL_DTYPE = torch.float16\n",
            "\n",
            "# ---- WikiText-2 Benchmark Protocol (Paper Sec. 5.1-5.2, Table 1) ----\n",
            "EVAL_SEQLEN     = 2048     # Paper: 2048-token non-overlapping evaluation chunks\n",
            "EVAL_MAX_CHUNKS = 20       # Set to None for full WikiText-2 test set (~140 chunks) or integer for faster run\n",
            "\n",
            "# ---- POT-PTQ Algorithm Hyperparameters (Paper Sec. 5.1) ----\n",
            "GROUP_SIZE     = 128      # Weight group size G (paper uses 64 or 128)\n",
            "CALIB_SEQS     = 16       # Calibration sequences (paper: 128 samples)\n",
            "CALIB_SEQLEN   = 1024     # Calibration sequence length (paper: 2048)\n",
            "EPOCHS_3BIT    = 3        # Step 2 fine-tuning epochs for 3-bit (paper: 10)\n",
            "EPOCHS_2BIT    = 5        # Step 2 fine-tuning epochs for 2-bit (paper: 40)\n",
            "QUANT_LR       = 1e-3     # Learning rate for learnable residual Gamma (paper Sec. 5.1)\n",
            "WEIGHT_DECAY   = 1e-1     # Regularization weight decay lambda (paper Sec. 5.1)\n",
            "\n",
            "print(f\"Target Model: {MODEL_NAME}\")\n",
            "print(f\"Group size: {GROUP_SIZE} | Calibration: {CALIB_SEQS} seqs x {CALIB_SEQLEN} tokens\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 2. Load 1B-Parameter Pretrained Model & Tokenizer"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from transformers import AutoModelForCausalLM, AutoTokenizer\n",
            "\n",
            "print(f\"Loading tokenizer for {MODEL_NAME}...\")\n",
            "tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)\n",
            "if tokenizer.pad_token is None:\n",
            "    tokenizer.pad_token = tokenizer.eos_token\n",
            "\n",
            "print(f\"Loading FP16 model weights for {MODEL_NAME}...\")\n",
            "model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=MODEL_DTYPE)\n",
            "model.to(DEVICE)\n",
            "model.eval()\n",
            "\n",
            "total_params = sum(p.numel() for p in model.parameters())\n",
            "print(f\"Loaded {MODEL_NAME} successfully: {total_params / 1e9:.3f}B parameters on {DEVICE}.\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 3. Prepare WikiText-2 Dataset (Paper Benchmark Split)\n",
            "\n",
            "- **Evaluation Dataset**: Standard WikiText-2 *test* split chunked into non-overlapping `EVAL_SEQLEN` (2048-token) windows (Table 1 protocol).\n",
            "- **Calibration Dataset**: `CALIB_SEQS` randomly sampled slices from the *train* split."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "from datasets import load_dataset\n",
            "\n",
            "print(\"Loading Salesforce/wikitext-2-raw-v1 dataset...\")\n",
            "wikitext_test = load_dataset(\"Salesforce/wikitext\", \"wikitext-2-raw-v1\", split=\"test\")\n",
            "wikitext_train = load_dataset(\"Salesforce/wikitext\", \"wikitext-2-raw-v1\", split=\"train\")\n",
            "\n",
            "test_text = \"\\n\\n\".join(wikitext_test[\"text\"])\n",
            "train_text = \"\\n\\n\".join(wikitext_train[\"text\"])\n",
            "\n",
            "test_ids = tokenizer(test_text, return_tensors=\"pt\").input_ids\n",
            "train_ids = tokenizer(train_text, return_tensors=\"pt\").input_ids\n",
            "print(f\"WikiText-2 Test Tokens:  {test_ids.shape[1]:,}\")\n",
            "print(f\"WikiText-2 Train Tokens: {train_ids.shape[1]:,}\")\n",
            "\n",
            "def get_calibration_batches(train_ids, n_seqs, seq_len, device, seed=0):\n",
            "    g = torch.Generator().manual_seed(seed)\n",
            "    max_start = train_ids.shape[1] - seq_len - 1\n",
            "    starts = torch.randint(0, max_start, (n_seqs,), generator=g)\n",
            "    return [train_ids[:, s:s + seq_len].to(device) for s in starts]\n",
            "\n",
            "calib_batches = get_calibration_batches(train_ids, CALIB_SEQS, CALIB_SEQLEN, DEVICE)\n",
            "print(f\"Prepared {len(calib_batches)} calibration sequences of length {CALIB_SEQLEN}.\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 4. Evaluate FP16 Baseline Perplexity on WikiText-2 (Table 1)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "@torch.no_grad()\n",
            "def evaluate_wikitext2_ppl(model, test_ids, seqlen, device, max_chunks=None):\n",
            "    model.eval()\n",
            "    n_chunks = test_ids.shape[1] // seqlen\n",
            "    if max_chunks is not None:\n",
            "        n_chunks = min(n_chunks, max_chunks)\n",
            "    nlls = []\n",
            "    for i in range(n_chunks):\n",
            "        batch = test_ids[:, i * seqlen:(i + 1) * seqlen].to(device)\n",
            "        out = model(batch, labels=batch)\n",
            "        nlls.append(out.loss.float() * seqlen)\n",
            "        if device == \"cuda\" and i % 10 == 0:\n",
            "            torch.cuda.empty_cache()\n",
            "    ppl = torch.exp(torch.stack(nlls).sum() / (n_chunks * seqlen))\n",
            "    return ppl.item(), n_chunks\n",
            "\n",
            "print(\"Evaluating FP16 baseline perplexity on WikiText-2...\")\n",
            "fp16_ppl, n_chunks_used = evaluate_wikitext2_ppl(model, test_ids, EVAL_SEQLEN, DEVICE, EVAL_MAX_CHUNKS)\n",
            "print(f\">> [FP16 Baseline] WikiText-2 Perplexity = {fp16_ppl:.3f} ({n_chunks_used} chunks of {EVAL_SEQLEN} tokens)\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 5. Algorithmic Implementation of POT-PTQ (Eq. 1–18, Algorithm 1 & 2)\n",
            "\n",
            "- **PoT Weight Formula (Eq. 1, 4)**: $W = S \\odot P \\odot 2^E$, where $P = \\text{sign}(W) \\in \\{-1, +1\\}$, $E = \\text{clamp}(\\text{round}(\\log_2(|W| / S)), 0, q_{\\max})$ with $q_{\\max} = 2^{n-1}-1$.\n",
            "- **Step 1 Grid Search (Algorithm 1, Sec. 3.2)**: Evaluates candidate multipliers $B = \\{0.01 \\cdot i \\mid i=1,\\dots,200\\}$ on $s_0 = \\max|W| / (2^{q_{\\max}-1})$ to select $s^* = s_0 \\cdot b^*$ minimizing weight reconstruction MSE.\n",
            "- **Step 2 Fine-Tuning with STE (Algorithm 2, Sec. 3.3)**: Learns group residual $\\hat{S}(\\Gamma) = S \\odot (1 + \\Gamma)$ using Straight-Through Estimator (STE) on layer output reconstruction loss $Q_2(\\Gamma) = \\|F(W, X) - F(W(\\Gamma), X)\\|_F^2 + \\frac{\\lambda}{2} \\|\\Gamma\\|_F^2$."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import copy, gc\n",
            "import torch.nn as nn\n",
            "import torch.nn.functional as F\n",
            "\n",
            "# ---------------- Straight-Through Estimator (Eq. 18) ----------------\n",
            "def ste_round_clamp(x: torch.Tensor, qmax: int) -> torch.Tensor:\n",
            "    rounded = torch.clamp(torch.round(x), 0, qmax)\n",
            "    return x + (rounded - x).detach()\n",
            "\n",
            "def qmax_for_bits(n_bits: int) -> int:\n",
            "    return (1 << (n_bits - 1)) - 1\n",
            "\n",
            "# ---------------- Group Reshaping (Eq. 5) ----------------\n",
            "def to_groups(W: torch.Tensor, group_size: int):\n",
            "    out_f, in_f = W.shape\n",
            "    pad = (-in_f) % group_size\n",
            "    if pad:\n",
            "        W = F.pad(W, (0, pad))\n",
            "    Wg = W.view(out_f, -1, group_size)\n",
            "    return Wg, pad\n",
            "\n",
            "def from_groups(Wg: torch.Tensor, pad: int, in_f: int):\n",
            "    W = Wg.reshape(Wg.shape[0], -1)\n",
            "    if pad:\n",
            "        W = W[:, :in_f]\n",
            "    return W\n",
            "\n",
            "# ---------------- Algorithm 1: Parallel Data-Agnostic Scale Init ----------------\n",
            "@torch.no_grad()\n",
            "def data_agnostic_scale_init(W: torch.Tensor, n_bits: int, group_size: int = 128,\n",
            "                             n_candidates: int = 200, device=None, chunk_rows: int = 256):\n",
            "    device = device or W.device\n",
            "    qmax = qmax_for_bits(n_bits)\n",
            "    Wf = W.to(device=device, dtype=torch.float32)\n",
            "    Wg, pad = to_groups(Wf, group_size)\n",
            "    out_f, n_groups, g_size = Wg.shape\n",
            "\n",
            "    P = torch.sign(Wg)\n",
            "    P[P == 0] = 1.0\n",
            "    absWg = Wg.abs()\n",
            "\n",
            "    denom = max(qmax, 1)\n",
            "    s0 = absWg.amax(dim=-1, keepdim=True) / float(denom)\n",
            "    s0 = torch.clamp(s0, min=1e-12)\n",
            "\n",
            "    B = torch.arange(1, n_candidates + 1, device=device, dtype=torch.float32) * 0.01\n",
            "    S = torch.empty((out_f, n_groups, 1), device=device, dtype=torch.float32)\n",
            "\n",
            "    # Memory-chunked GPU parallel grid search over output rows\n",
            "    for start in range(0, out_f, chunk_rows):\n",
            "        end = min(start + chunk_rows, out_f)\n",
            "        Wg_c = Wg[start:end]\n",
            "        s0_c = s0[start:end]\n",
            "        P_c = P[start:end]\n",
            "        absW_c = absWg[start:end]\n",
            "\n",
            "        sb = s0_c.unsqueeze(-1) * B.view(1, 1, 1, -1)\n",
            "        sb = torch.clamp(sb, min=1e-12)\n",
            "\n",
            "        absW_exp = absW_c.unsqueeze(-1)\n",
            "        log_ratio = torch.log2(torch.clamp(absW_exp / sb, min=1e-12))\n",
            "        E = torch.clamp(torch.round(log_ratio), 0, qmax)\n",
            "\n",
            "        Wg_hat = sb * P_c.unsqueeze(-1) * torch.pow(2.0, E)\n",
            "        Q1 = ((Wg_c.unsqueeze(-1) - Wg_hat) ** 2).sum(dim=2)\n",
            "        best_idx = torch.argmin(Q1, dim=-1)\n",
            "        b_star = B[best_idx]\n",
            "        S[start:end] = (s0_c.squeeze(-1) * b_star).unsqueeze(-1)\n",
            "\n",
            "    return S, P, pad\n",
            "\n",
            "# ---------------- PoTLinear Module (Eq. 15-18) ----------------\n",
            "class PoTLinear(nn.Module):\n",
            "    def __init__(self, linear: nn.Linear, n_bits: int, group_size: int = 128,\n",
            "                 compute_dtype: torch.dtype = torch.float16, init_method: str = \"step1\"):\n",
            "        super().__init__()\n",
            "        self.in_features = linear.in_features\n",
            "        self.out_features = linear.out_features\n",
            "        self.n_bits = n_bits\n",
            "        self.group_size = group_size\n",
            "        self.qmax = qmax_for_bits(n_bits)\n",
            "        self.compute_dtype = compute_dtype\n",
            "\n",
            "        W = linear.weight.data.clone().float()\n",
            "        n_cands = 200 if init_method == \"step1\" else 1\n",
            "        S, P, pad = data_agnostic_scale_init(W, n_bits=n_bits, group_size=group_size, n_candidates=n_cands, chunk_rows=256)\n",
            "        self.pad = pad\n",
            "        self.register_buffer(\"W_orig_grouped\", to_groups(W, group_size)[0])\n",
            "        self.register_buffer(\"P\", P)\n",
            "        self.register_buffer(\"S\", S)\n",
            "        self.Gamma = nn.Parameter(torch.zeros_like(S))\n",
            "        self.bias = nn.Parameter(linear.bias.data.clone().to(compute_dtype)) if linear.bias is not None else None\n",
                        "    def dequantized_weight(self, use_ste: bool = True):\n",
            "        if self.W_orig_grouped is None and hasattr(self, \"E\"):\n",
            "            Wg_hat = self.S * self.P * torch.pow(2.0, self.E.to(self.compute_dtype))\n",
            "            return from_groups(Wg_hat, self.pad, self.in_features).to(self.compute_dtype)\n",
            "        Shat = self.S * (1.0 + self.Gamma)\n",
            "        Shat_safe = torch.clamp(Shat.abs(), min=1e-12) * torch.sign(Shat + 1e-12)\n",
            "        absW = self.W_orig_grouped.abs()\n",
            "        log_ratio = torch.log2(torch.clamp(absW / Shat_safe.abs(), min=1e-12))\n",
            "        if use_ste or (self.Gamma is not None and self.Gamma.requires_grad):\n",
            "            E = ste_round_clamp(log_ratio, self.qmax)\n",
            "        else:\n",
            "            E = torch.clamp(torch.round(log_ratio), 0, self.qmax)\n",
            "        Wg_hat = Shat_safe * self.P * torch.pow(2.0, E)\n",
            "        return from_groups(Wg_hat, self.pad, self.in_features).to(self.compute_dtype)\n",
            "\n",
            "    def forward(self, x):\n",
            "        W_hat = self.dequantized_weight(use_ste=(self.training or (self.Gamma is not None and self.Gamma.requires_grad)))\n",
            "        bias = self.bias if self.bias is not None else None\n",
            "        return F.linear(x.to(self.compute_dtype), W_hat, bias)\n",
            "\n",
            "    @torch.no_grad()\n",
            "    def freeze(self):\n",
            "        self.S.mul_(1.0 + self.Gamma)\n",
            "        self.Gamma.zero_()\n",
            "        self.Gamma.requires_grad_(False)\n",
            "        if self.W_orig_grouped is not None:\n",
            "            absW = self.W_orig_grouped.abs()\n",
            "            log_ratio = torch.log2(torch.clamp(absW / self.S.abs().clamp(min=1e-12), min=1e-12))\n",
            "            self.register_buffer(\"E\", torch.clamp(torch.round(log_ratio), 0, self.qmax).to(torch.int8))\n",
            "            self.W_orig_grouped = None\n",
            "\n",
            "    @torch.no_grad()\n",
            "    def weight_only_mse(self):\n",
            "        if self.W_orig_grouped is None:\n",
            "            return 0.0\n",
            "        W_hat = self.dequantized_weight(use_ste=False).float()\n",
            "        Wg_hat, _ = to_groups(W_hat, self.group_size)\n",
            "        return ((Wg_hat - self.W_orig_grouped) ** 2).mean().item()\n",
            "\n",
            "print(\"POT-PTQ Core Algorithm components ready.\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 6. Layer-Wise Sequential Calibration Driver (Algorithm 2)\n",
            "\n",
            "Sequential calibration processes each transformer block one at a time, passing the newly quantized block's output directly as input to the subsequent block. Only a single block is held in memory for fine-tuning."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "class StopForward(Exception):\n",
            "    pass\n",
            "\n",
            "def get_transformer_blocks(model):\n",
            "    candidate_paths = [\"model.layers\", \"gpt_neox.layers\", \"transformer.h\", \"model.decoder.layers\", \"transformer.blocks\"]\n",
            "    for path in candidate_paths:\n",
            "        obj = model\n",
            "        ok = True\n",
            "        for part in path.split(\".\"):\n",
            "            if hasattr(obj, part):\n",
            "                obj = getattr(obj, part)\n",
            "            else:\n",
            "                ok = False\n",
            "                break\n",
            "        if ok and isinstance(obj, (nn.ModuleList, list)):\n",
            "            return obj\n",
            "    raise ValueError(\"Could not find transformer block list.\")\n",
            "\n",
            "def get_linear_submodules(block):\n",
            "    return {name: mod for name, mod in block.named_modules() if isinstance(mod, nn.Linear) and not isinstance(mod, PoTLinear)}\n",
            "\n",
            "def set_submodule(root, dotted_name, new_module):\n",
            "    parts = dotted_name.split(\".\")\n",
            "    obj = root\n",
            "    for p in parts[:-1]:\n",
            "        obj = getattr(obj, p)\n",
            "    setattr(obj, parts[-1], new_module)\n",
            "\n",
            "@torch.no_grad()\n",
            "def _detach_clone(x):\n",
            "    if torch.is_tensor(x):\n",
            "        return x.detach().clone()\n",
            "    elif isinstance(x, tuple):\n",
            "        return tuple(_detach_clone(v) for v in x)\n",
            "    elif isinstance(x, dict):\n",
            "        return {k: _detach_clone(v) for k, v in x.items()}\n",
            "    return x\n",
            "\n",
            "def capture_first_block_inputs(model, first_block, calib_batches):\n",
            "    captured = []\n",
            "    def hook(module, args, kwargs):\n",
            "        captured.append((_detach_clone(args), _detach_clone(kwargs)))\n",
            "        raise StopForward()\n",
            "    handle = first_block.register_forward_pre_hook(hook, with_kwargs=True)\n",
            "    try:\n",
            "        for batch in calib_batches:\n",
            "            try:\n",
            "                model(batch, use_cache=False)\n",
            "            except (TypeError, AttributeError):\n",
            "                try:\n",
            "                    model(batch)\n",
            "                except StopForward:\n",
            "                    pass\n",
            "            except StopForward:\n",
            "                pass\n",
            "    finally:\n",
            "        handle.remove()\n",
            "    return captured\n",
            "\n",
            "def quantize_model(model, calib_batches, n_bits, group_size=128, epochs=10, lr=1e-3,\n",
            "                    weight_decay=1e-1, init_method=\"step1\", device=\"cuda\", compute_dtype=torch.float16, verbose=True):\n",
            "    model.eval()\n",
            "    for p in model.parameters():\n",
            "        p.requires_grad_(False)\n",
            "    blocks = get_transformer_blocks(model)\n",
            "    n_blocks = len(blocks)\n",
            "    \n",
            "    current_inps = capture_first_block_inputs(model, blocks[0], calib_batches)\n",
            "    stats = []\n",
            "\n",
            "    for i, block in enumerate(blocks):\n",
            "        orig_block = copy.deepcopy(block).to(device)\n",
            "        orig_block.eval()\n",
            "        for p in orig_block.parameters():\n",
            "            p.requires_grad_(False)\n",
            "\n",
            "        H_orig_list = []\n",
            "        with torch.no_grad():\n",
            "            for args, kwargs in current_inps:\n",
            "                a_dev = tuple(a.to(device) if torch.is_tensor(a) else a for a in args)\n",
            "                k_dev = {k: (v.to(device) if torch.is_tensor(v) else v) for k, v in kwargs.items()}\n",
            "                out = orig_block(*a_dev, **k_dev)\n",
            "                H_orig_list.append((out[0] if isinstance(out, tuple) else out).detach().clone())\n",
            "\n",
            "        del orig_block\n",
            "        if device == \"cuda\":\n",
            "            torch.cuda.empty_cache()\n",
            "\n",
            "        linears = get_linear_submodules(block)\n",
            "        pot_layers = {}\n",
            "        for name, lin in linears.items():\n",
            "            pot = PoTLinear(lin, n_bits=n_bits, group_size=group_size, compute_dtype=compute_dtype, init_method=init_method).to(device)\n",
            "            pot_layers[name] = pot\n",
            "            set_submodule(block, name, pot)\n",
            "\n",
            "        params = [pot.Gamma for pot in pot_layers.values()]\n",
            "        for p in params:\n",
            "            p.requires_grad_(True)\n",
            "        opt = torch.optim.Adam(params, lr=lr)\n",
            "        last_loss = 0.0\n",
            "\n",
            "        if epochs > 0 and len(current_inps) > 0:\n",
            "            for epoch in range(epochs):\n",
            "                for idx, (args, kwargs) in enumerate(current_inps):\n",
            "                    a_dev = tuple(a.to(device) if torch.is_tensor(a) else a for a in args)\n",
            "                    k_dev = {k: (v.to(device) if torch.is_tensor(v) else v) for k, v in kwargs.items()}\n",
            "                    Horig = H_orig_list[idx]\n",
            "\n",
            "                    Hquant = block(*a_dev, **k_dev)\n",
            "                    Hquant = Hquant[0] if isinstance(Hquant, tuple) else Hquant\n",
            "\n",
            "                    rec_loss = F.mse_loss(Horig.float(), Hquant.float())\n",
            "                    reg = sum((p.float() ** 2).mean() for p in params)\n",
            "                    loss = rec_loss + (weight_decay / 2.0) * reg\n",
            "\n",
            "                    opt.zero_grad()\n",
            "                    loss.backward()\n",
            "                    opt.step()\n",
            "                    last_loss = rec_loss.item()\n",
            "\n",
            "        avg_w_mse = sum(pot.weight_only_mse() for pot in pot_layers.values()) / max(len(pot_layers), 1)\n",
            "        for pot in pot_layers.values():\n",
            "            pot.freeze()\n",
            "\n",
            "        next_inps = []\n",
            "        with torch.no_grad():\n",
            "            for args, kwargs in current_inps:\n",
            "                a_dev = tuple(a.to(device) if torch.is_tensor(a) else a for a in args)\n",
            "                k_dev = {k: (v.to(device) if torch.is_tensor(v) else v) for k, v in kwargs.items()}\n",
            "                out = block(*args_dev, **kwargs_dev)\n",
            "                if len(a_dev) > 0:\n",
            "                    new_args = (out[0] if isinstance(out, tuple) else out,) + a_dev[1:]\n",
            "                    new_kwargs = k_dev\n",
            "                else:\n",
            "                    new_args = a_dev\n",
            "                    new_kwargs = dict(k_dev)\n",
            "                    new_kwargs[\"hidden_states\"] = out[0] if isinstance(out, tuple) else out\n",
            "                next_inps.append((_detach_clone(new_args), _detach_clone(new_kwargs)))\n",
            "\n",
            "        current_inps = next_inps\n",
            "        del H_orig_list\n",
            "        del opt\n",
            "        del params\n",
            "        stats.append({\"block\": i, \"recon_loss\": last_loss, \"weight_mse\": avg_w_mse})\n",
            "        if verbose:\n",
            "            print(f\"  [block {i:2d}/{n_blocks-1}] output-recon MSE={last_loss:.6e}  avg weight MSE={avg_w_mse:.6e}\", flush=True)\n",
            "        if device == \"cuda\":\n",
            "            torch.cuda.empty_cache()\n",
            "            gc.collect()\n",
            "\n",
            "    return model, stats\n",
            "\n",
            "print(\"Layer-wise Sequential Calibration Driver ready.\")\n"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 7. Run POT-PTQ at 3-bit and 2-bit & Evaluate Perplexity (Table 1 Style)"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "results = {\"FP16 Baseline\": fp16_ppl}\n",
            "quantized_models = {}\n",
            "\n",
            "for n_bits, epochs in [(3, EPOCHS_3BIT), (2, EPOCHS_2BIT)]:\n",
            "    print(f\"\\n===== POT-PTQ {n_bits}-bit (Step 1 + Step 2, {epochs} epochs) =====\")\n",
            "    qmodel = copy.deepcopy(model).to(DEVICE)\n",
            "    qmodel, stats = quantize_model(\n",
            "        model=qmodel,\n",
            "        calib_batches=calib_batches,\n",
            "        n_bits=n_bits,\n",
            "        group_size=GROUP_SIZE,\n",
            "        epochs=epochs,\n",
            "        lr=QUANT_LR,\n",
            "        weight_decay=WEIGHT_DECAY,\n",
            "        init_method=\"step1\",\n",
            "        device=DEVICE,\n",
            "        compute_dtype=MODEL_DTYPE,\n",
            "        verbose=True,\n",
            "    )\n",
            "    ppl, _ = evaluate_wikitext2_ppl(qmodel, test_ids, EVAL_SEQLEN, DEVICE, EVAL_MAX_CHUNKS)\n",
            "    print(f\">> [POT-PTQ {n_bits}-bit] WikiText-2 Perplexity = {ppl:.3f}\", flush=True)\n",
            "    results[f\"POT-PTQ {n_bits}-bit\"] = ppl\n",
            "    quantized_models[n_bits] = qmodel\n",
            "\n",
            "print(\"\\n\" + \"=\"*50)\n",
            "print(\"       WIKITEXT-2 PERPLEXITY RESULTS (TABLE 1 STYLE)\")\n",
            "print(\"=\"*50)\n",
            "for k, v in results.items():\n",
            "    print(f\"  {k:<22}: {v:8.3f}\")\n",
            "print(\"=\"*50)"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 8. Ablation Study: Step 1 vs. Step 2 vs. Full Method (Table 4 Style)\n",
            "\n",
            "Ablation at 2-bit confirms the paper's core insight:\n",
            "- **Step 1 Only**: Grid search provides a strong mathematical starting point without activations.\n",
            "- **Step 2 Only (naive init)**: Fine-tuning from $b=1$ suffers due to poor exponent discretization.\n",
            "- **Step 1 + Step 2**: Combines robust scale initialization with output-level alignment."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"===== 2-bit Ablation Study (Table 4 Style) =====\\n\")\n",
            "\n",
            "# 1. Step 1 only (no fine-tuning, Gamma=0)\n",
            "print(\"Evaluating Step 1 Only (Scale Init, no fine-tuning)...\", flush=True)\n",
            "qm_s1 = copy.deepcopy(model).to(DEVICE)\n",
            "qm_s1, _ = quantize_model(qm_s1, calib_batches, n_bits=2, group_size=GROUP_SIZE,\n",
            "                         epochs=0, lr=QUANT_LR, weight_decay=WEIGHT_DECAY,\n",
            "                         init_method=\"step1\", device=DEVICE, compute_dtype=MODEL_DTYPE, verbose=False)\n",
            "ppl_s1, _ = evaluate_wikitext2_ppl(qm_s1, test_ids, EVAL_SEQLEN, DEVICE, EVAL_MAX_CHUNKS)\n",
            "del qm_s1\n",
            "if DEVICE == \"cuda\": torch.cuda.empty_cache()\n",
            "\n",
            "# 2. Step 2 only (naive b=1 scale init without Step 1 grid search)\n",
            "print(\"Evaluating Step 2 Only (naive b=1 scale init)...\", flush=True)\n",
            "qm_s2 = copy.deepcopy(model).to(DEVICE)\n",
            "qm_s2, _ = quantize_model(qm_s2, calib_batches, n_bits=2, group_size=GROUP_SIZE,\n",
            "                         epochs=EPOCHS_2BIT, lr=QUANT_LR, weight_decay=WEIGHT_DECAY,\n",
            "                         init_method=\"naive\", device=DEVICE, compute_dtype=MODEL_DTYPE, verbose=False)\n",
            "ppl_s2, _ = evaluate_wikitext2_ppl(qm_s2, test_ids, EVAL_SEQLEN, DEVICE, EVAL_MAX_CHUNKS)\n",
            "del qm_s2\n",
            "if DEVICE == \"cuda\": torch.cuda.empty_cache()\n",
            "\n",
            "print(\"\\n\" + \"=\"*50)\n",
            "print(\"             2-BIT ABLATION SUMMARY (TABLE 4 STYLE)\")\n",
            "print(\"=\"*50)\n",
            "print(f\"  Step 1 Only                  : perplexity = {ppl_s1:.3f}\")\n",
            "print(f\"  Step 2 Only (naive b=1 init) : perplexity = {ppl_s2:.3f}\")\n",
            "print(f\"  Step 1 + Step 2 (Full Method): perplexity = {results['POT-PTQ 2-bit']:.3f}\")\n",
            "print(\"=\"*50)"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 9. Hardware-Friendly Bitwise Dequantization Microbenchmark (Section 4, Table 6)\n",
            "\n",
            "Demonstrates the IEEE 754 bit-manipulation and integer addition speedup on the local GPU."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "import time\n",
            "from pot_ptq.core import dequant_naive_fp, dequant_bitwise\n",
            "\n",
            "torch.manual_seed(0)\n",
            "n = 1_000_000\n",
            "scale = (torch.rand(n, device=DEVICE) * 0.05 + 1e-3).to(torch.float16)\n",
            "sign = torch.where(torch.rand(n, device=DEVICE) > 0.5, 1.0, -1.0).to(torch.float16)\n",
            "exponent = torch.randint(0, 4, (n,), device=DEVICE)\n",
            "\n",
            "w_naive = dequant_naive_fp(scale, sign, exponent)\n",
            "w_bitwise = dequant_bitwise(scale, sign, exponent)\n",
            "max_err = (w_naive.float() - w_bitwise.float()).abs().max().item()\n",
            "print(f\"Bitwise dequant correctness: max abs error = {max_err:.6e} (Exact Match: {torch.allclose(w_naive.float(), w_bitwise.float())})\")\n",
            "\n",
            "def timeit(fn, iters=50):\n",
            "    if DEVICE == \"cuda\":\n",
            "        torch.cuda.synchronize()\n",
            "    t0 = time.perf_counter()\n",
            "    for _ in range(iters):\n",
            "        fn(scale, sign, exponent)\n",
            "    if DEVICE == \"cuda\":\n",
            "        torch.cuda.synchronize()\n",
            "    return (time.perf_counter() - t0) / iters\n",
            "\n",
            "t_fp = timeit(dequant_naive_fp)\n",
            "t_bit = timeit(dequant_bitwise)\n",
            "print(f\"Uniform FP16 Float Multiply : {t_fp * 1e3:.4f} ms\")\n",
            "print(f\"PoT Bitwise + Int Add       : {t_bit * 1e3:.4f} ms\")\n",
            "print(f\"Kernel Speedup              : {t_fp / max(t_bit, 1e-9):.2f}x\")"
        ]
    },
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "## 10. Text Generation Quality Demonstration"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "prompt = \"The history of artificial intelligence began\"\n",
            "input_ids = tokenizer(prompt, return_tensors=\"pt\").input_ids.to(DEVICE)\n",
            "\n",
            "print(f\"Prompt: \\\"{prompt}\\\"\\n\")\n",
            "for n_bits, qm in quantized_models.items():\n",
            "    qm.eval()\n",
            "    with torch.no_grad():\n",
            "        out = qm.generate(input_ids, max_new_tokens=40, do_sample=True,\n",
            "                           temperature=0.8, top_k=50, pad_token_id=tokenizer.pad_token_id)\n",
            "    print(f\"--- {n_bits}-bit POT-PTQ Generation ---\")\n",
            "    print(tokenizer.decode(out[0], skip_special_tokens=True))\n",
            "    print()"
        ]
    }
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

with open("POT_PTQ_1B_reproduction.ipynb", "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)

print("POT_PTQ_1B_reproduction.ipynb updated successfully!")
